  // Generic font families and global values (all case-insensitive)
 export const keywordsList = [
    { id: 1, name: "serif" },
    { id: 2, name: "sans-serif" },
    { id: 3, name: "cursive" },
    { id: 4, name: "fantasy" },
    { id: 5, name: "system-ui" },
    { id: 6, name: "monospace" },
    { id: 7, name: "ui-serif" },
    { id: 8, name: "ui-sans-serif" },
    { id: 9, name: "ui-monospace" },
    { id: 10, name: "ui-rounded" },
    { id: 11, name: "math" },
    { id: 12, name: "emoji" },
    { id: 13, name: "fangsong" },
    { id: 14, name: "inherit" },
    { id: 15, name: "initial" },
    { id: 16, name: "revert" },
    { id: 17, name: "revert-layer" },
    { id: 18, name: "unset" },
    { id: 19, name: "BlinkMacSystemFont" },
    { id: 20, name: "-apple-system" },
    { id: 21, name: "-apple-system-body" },
    { id: 22, name: "-apple-system-headline" },
    { id: 23, name: "-apple-system-subheadline" },
    { id: 24, name: "-apple-system-caption1" },
    { id: 25, name: "-apple-system-caption2" },
    { id: 26, name: "-apple-system-footnote" },
    { id: 27, name: "-apple-system-short-body" },
    { id: 28, name: "-apple-system-short-headline" },
    { id: 29, name: "-apple-system-short-subheadline" },
    { id: 30, name: "-apple-system-short-caption1" },
    { id: 31, name: "-apple-system-short-footnote" },
    { id: 32, name: "-apple-system-tall-body" },
  ];
